# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/checkout@master
      with:
        repository: mitzey234/PluginReferences
        path: ./PluginRefs
        token: ${{ secrets.my_pat }}
        
    - name: Test
      run: ls

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore MirrorPatch.sln

    - name: Build solution
      run: msbuild MirrorPatch.sln -t:rebuild -property:Configuration=Release
